### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by koraa** [rosenpass/rosenpass#62] opened 2023-05-11 11:32 UTC
The nix runners on the CI are failing for some reason; I think these might be false positives but they do make us look bad. Running for prolonged times with a read CI also establishes a culture of disregarding the CI output which can lead to real bugs being introduced. Please make sure that the CI is green if the code on main is acceptable as it is.

**Comment by wucke13** [comment] 2023-05-11 11:44
I think you mean the CI failure on main, correct? If so, the [Nix actions actually pass](https://github.com/rosenpass/rosenpass/actions/runs/4817193393). The error is in [the QC workflow](https://github.com/rosenpass/rosenpass/actions/runs/4817193395/jobs/8846778767#step:6:161), which is not Nix based. In particular, it looks like internal compiler error (ICE) on the rust compiler while generating the docs. I can not reproduce this failure locally with running `RUSTDOCFLAGS="-D warnings" cargo doc --document-private-items`.

**Comment by koraa** [comment] 2023-05-22 21:03
I am going to disable these jobs for now until we have a fix,

**Comment by koraa** [comment] 2023-05-23 06:27
I think I was able to work around the CI failure by deactivating the failing cross compilation, using `cargo doc --no-deps` and finally I had to escape the usages of `<...>` and `[...]` in the documentation introduced in #56 because they where confusing the markdown parser.

I think what we can learn from this is that we should keep the CI green even if this means introducing workarounds because if we don't failures like this can accumulate.

**Comment by stv0g** [comment] 2023-09-01 15:47
The CI is working fine again: https://github.com/rosenpass/rosenpass/actions/runs/6017880848

Lets close this issue.

**Closed by stv0g** 2023-09-01 15:47 UTC
Labels: bug, CI
